const FALLBACK = [
  {id:'ailhat',name:'Ailhat',summary:'AI product intelligence and market-gap detection platform.',stage:'private-beta-prelaunch',readinessPct:65,firstPaidClient:'needs assessment',url:'https://ailhat.vercel.app/'},
  {id:'alvira',name:'ALVIRA',summary:'Context-intelligence / operating-system platform.',stage:'active ecosystem product',readinessPct:null,firstPaidClient:'needs assessment',url:'https://alviratech.vercel.app/'},
  {id:'bridge',name:'ALVIRA Bridge',summary:'ALVIRA ecosystem integration layer.',stage:'active ecosystem product',readinessPct:null,firstPaidClient:'needs assessment',url:'https://alviratech-bridge.vercel.app/'},
  {id:'ledgato',name:'Ledgato',summary:'Authorization and security control plane for AI agents.',stage:'active product update',readinessPct:null,firstPaidClient:'needs assessment',url:'https://ledgato.vercel.app/'},
  {id:'policyguard',name:'PolicyGuard',summary:'AI policy, governance, and control product.',stage:'needs assessment',readinessPct:null,firstPaidClient:'needs assessment'},
  {id:'websitehero',name:'WEBSITEHERO',summary:'Website-focused product.',stage:'needs assessment',readinessPct:null,firstPaidClient:'needs assessment'},
  {id:'trendvault',name:'TrendVault',summary:'Trend-focused product.',stage:'needs assessment',readinessPct:null,firstPaidClient:'needs assessment'},
  {id:'adscale-pro',name:'AdScale Pro',summary:'Advertising / growth product.',stage:'needs assessment',readinessPct:null,firstPaidClient:'needs assessment'}
];
const SECTIONS = [
  {key:'identity',label:'Identity',questions:[
    ['name','Agent name','What is this agent called?','text',true],
    ['primaryFunction','Primary function','What is the agent primarily responsible for?','textarea',true],
    ['environment','Environment','Where does the agent operate?','select',true,['Internal workflow','Customer-facing application','CRM','Support platform','Development environment','Research environment','Other']],
    ['users','Primary users','Who relies on this agent?','textarea',true]
  ]},
  {key:'capability',label:'Capability',questions:[
    ['capabilities','Current capabilities','What can the agent currently accomplish?','multi',true,['Generate','Analyze','Search','Summarize','Classify','Recommend','Execute','Automate','Communicate','Monitor']],
    ['tools','Tool access','What tools or systems can the agent access?','textarea',true],
    ['executionLevel','Execution level','How independently can it act?','select',true,['Informational only','Recommendation','Human-approved execution','Autonomous execution']],
    ['confidence','Capability confidence','How confident are you in its current capabilities?','scale',true]
  ]},
  {key:'context',label:'Context',questions:[
    ['currentKnowledge','Current knowledge','What does the agent already know about the business, workflow, users, or environment?','textarea',true],
    ['missingContext','Missing context','What information is missing?','textarea',true],
    ['sourcesOfTruth','Sources of truth','Where should the agent obtain authoritative information?','multi',true,['Documentation','Database','CRM','Knowledge base','Policies','APIs','Human experts','Previous conversations']],
    ['userSpecificContext','User-specific context','Does the agent need information about individual users or preferences?','select',true,['No','Sometimes','Frequently','Essential']],
    ['quality','Context quality','Rate the current context.','scale',true]
  ]},
  {key:'performance',label:'Performance',questions:[
    ['strengths','What works?','What does the agent consistently do well?','textarea',true],
    ['failures','Where does it fail?','Where does the agent currently break down?','textarea',true],
    ['intervention','Human intervention','How often does a human need to intervene?','select',true,['Never','Rarely','Sometimes','Frequently','Almost always','Unknown']],
    ['failureSeverity','Failure severity','What happens when the agent gets something wrong?','select',true,['Low impact','Moderate impact','High impact','Critical']],
    ['reliability','Reliability confidence','Rate current reliability.','scale',true]
  ]},
  {key:'objective',label:'Objective',questions:[
    ['primaryObjective','Primary objective','What should this agent ultimately accomplish?','textarea',true],
    ['desiredOutcome','Desired outcome','What would “working well” look like?','textarea',true],
    ['highestValueImprovement','Highest-value improvement','What is the single most valuable thing to improve?','textarea',true],
    ['successMetric','Success metric','How should improvement be measured?','select',true,['Time saved','Accuracy','Completion rate','Human intervention','Revenue','Cost reduction','Response time','Customer satisfaction','Error rate']],
    ['priority','Priority','How important is improvement right now?','select',true,['Low','Medium','High','Critical']]
  ]}
];
let products=FALLBACK.slice();
const KEY='agent-control-assessments-v1';
const WORK='agent-control-work-v1';
const state={agent:null,section:0,data:{},results:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function allAssessments(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function saveAssessments(x){localStorage.setItem(KEY,JSON.stringify(x))}
function assessmentFor(id){return allAssessments()[id]||null}
function saveCurrent(){if(!state.agent)return;const all=allAssessments();all[state.agent.id]={agentId:state.agent.id,status:'in_progress',currentSection:state.section,data:state.data,updatedAt:new Date().toISOString()};saveAssessments(all);}
function hasValue(v){return Array.isArray(v)?v.length>0:v!==undefined&&v!==null&&String(v).trim()!==''}
function validSection(){const sec=SECTIONS[state.section];return sec.questions.filter(q=>q[4]).every(q=>hasValue(state.data[q[0]]))}
function startAssessment(id){state.agent=products.find(p=>p.id===id)||products[0];const saved=assessmentFor(id);state.section=saved?.currentSection||0;state.data=saved?.data||{name:state.agent.name};state.results=saved?.results||null;document.getElementById('assessment').classList.add('open');renderAssessment();}
function renderAssessment(){if(!state.agent)return;const sec=SECTIONS[state.section];const pct=Math.round((state.section/SECTIONS.length)*100);document.getElementById('assessment').innerHTML=`<div class="a-top"><div><span class="ey">ASSESSMENT</span><h1>${esc(state.agent.name)}</h1></div><button onclick="closeAssessment()">Close</button></div><div class="a-layout"><aside class="steps">${SECTIONS.map((s,i)=>`<button class="step ${i===state.section?'active':''} ${i<state.section?'done':''}" onclick="jumpSection(${i})"><b>${String(i+1).padStart(2,'0')}</b><span>${s.label}</span>${i<state.section?'✓':''}</button>`).join('')}<div class="progress"><i style="width:${pct}%"></i></div><small>${pct}% complete</small></aside><main class="a-main"><div class="section-kicker">${String(state.section+1).padStart(2,'0')} / ${SECTIONS.length}</div><h2>${sec.label}</h2><p class="intro">Answer what you know. Unknown information stays unknown and becomes part of the recommendation.</p>${sec.questions.map(renderQuestion).join('')}<div class="actions"><button onclick="closeAssessment()">Save & Exit</button>${state.section>0?'<button onclick="prevSection()">Back</button>':''}${state.section<SECTIONS.length-1?'<button class="primary" onclick="nextSection()">Save & Continue →</button>':'<button class="primary" onclick="completeAssessment()">Complete Assessment →</button>'}</div></main><aside class="context"><span class="ey">AGENT</span><strong>${esc(state.agent.name)}</strong><span class="tag">${esc(state.agent.stage)}</span><div class="metric"><small>STATUS</small><b>${assessmentFor(state.agent.id)?.status==='completed'?'ASSESSED':'ASSESSING'}</b></div><div class="metric"><small>COMPLETION</small><b>${pct}%</b></div><div class="metric"><small>PRIMARY QUESTION</small><p>What does this agent need to become reliably useful?</p></div></aside></div>`;}
function renderQuestion(q){const [key,label,help,type,required,opts]=q;let v=state.data[key];let body='';if(type==='textarea')body=`<textarea data-k="${key}" placeholder="Type your answer…">${esc(v||'')}</textarea>`;else if(type==='text')body=`<input data-k="${key}" value="${esc(v||'')}" placeholder="Type your answer…">`;else if(type==='select')body=`<select data-k="${key}"><option value="">Select…</option>${opts.map(o=>`<option ${v===o?'selected':''}>${esc(o)}</option>`).join('')}</select>`;else if(type==='scale')body=`<div class="scale">${[1,2,3,4,5].map(n=>`<button class="scale-btn ${v===n?'selected':''}" data-k="${key}" onclick="setScale('${key}',${n})"><b>${n}</b><span>${['Unknown','Limited','Moderate','Strong','Very strong'][n-1]}</span></button>`).join('')}</div>`;else if(type==='multi')body=`<div class="chips">${opts.map(o=>`<button class="chip ${(v||[]).includes(o)?'selected':''}" onclick="toggleMulti('${key}',${JSON.stringify(o).replace(/"/g,'&quot;')})">${esc(o)}</button>`).join('')}</div>`;return `<section class="q"><label>${esc(label)} ${required?'<em>*</em>':''}</label><p>${esc(help)}</p>${body}</section>`}
function capture(){document.querySelectorAll('[data-k]').forEach(el=>{if(el.tagName==='INPUT'||el.tagName==='TEXTAREA'||el.tagName==='SELECT')state.data[el.dataset.k]=el.value});saveCurrent()}
function nextSection(){capture();if(!validSection()){alert('Complete the required fields in this section before continuing.');return}state.section++;saveCurrent();renderAssessment()}
function prevSection(){capture();state.section--;saveCurrent();renderAssessment()}
function jumpSection(i){capture();if(i>state.section&&!validSection()){alert('Complete the required fields in this section before continuing.');return}state.section=i;saveCurrent();renderAssessment()}
function setScale(k,n){state.data[k]=n;saveCurrent();renderAssessment()}
function toggleMulti(k,o){const a=state.data[k]||[];state.data[k]=a.includes(o)?a.filter(x=>x!==o):[...a,o];saveCurrent();renderAssessment()}
function closeAssessment(){capture();document.getElementById('assessment').classList.remove('open');renderPortfolio()}
function score(){const d=state.data;const context=(Number(d.quality)||0)*20;const capability=(Number(d.confidence)||0)*20;let reliability=(Number(d.reliability)||0)*20;let toolAccess=(d.tools?80:0);if(d.capabilities?.length)toolAccess=Math.min(100,toolAccess+d.capabilities.length*3);let objective=(d.primaryObjective&&d.desiredOutcome&&d.successMetric?90:50);return {context,capability,reliability,toolAccess,objective,overall:Math.round((context+capability+reliability+toolAccess+objective)/5)}}
function recommendation(r){const dims=[['context',r.context,'Build Context Package'],['capability',r.capability,'Expand Capability'],['reliability',r.reliability,'Improve Reliability'],['toolAccess',r.toolAccess,'Connect Tools'],['objective',r.objective,'Define Agent Objective']].sort((a,b)=>a[1]-b[1]);const gap=dims[0];const copy={context:'The agent needs stronger business-specific knowledge, rules, and sources of truth.',capability:'The agent needs a clearer or broader capability set to accomplish its intended job.',reliability:'The agent needs reliability work, evaluation, or guardrails before broader execution.',toolAccess:'The agent needs access to the systems and tools required to perform its job.',objective:'The desired outcome and success criteria need to be made explicit.'};return {gap:gap[0],title:gap[2],description:copy[gap[0]]}}
function completeAssessment(){capture();if(!SECTIONS.every((_,i)=>i===SECTIONS.length-1||true)||!validSection()){alert('Complete the required fields in this section before finishing.');return}const r=score(),rec=recommendation(r);const all=allAssessments();all[state.agent.id]={agentId:state.agent.id,status:'completed',currentSection:5,data:state.data,results:{...r,...rec},updatedAt:new Date().toISOString()};saveAssessments(all);state.results={...r,...rec};state.section=5;renderResults();}
function renderResults(){const r=state.results||score(),rec=state.results?.title?state.results:recommendation(r);document.getElementById('assessment').innerHTML=`<div class="a-top"><div><span class="ey">ASSESSMENT COMPLETE</span><h1>${esc(state.agent.name)}</h1></div><button onclick="closeAssessment()">Close</button></div><main class="results"><div class="result-hero"><span class="ey">READINESS</span><strong>${r.overall}</strong><small>/ 100</small></div><div class="dimensions">${[['Context',r.context],['Capability',r.capability],['Reliability',r.reliability],['Tool Access',r.toolAccess],['Objective Clarity',r.objective]].map(x=>`<div><span>${x[0]}</span><b>${x[1]}</b><i><em style="width:${x[1]}%"></em></i></div>`).join('')}</div><section class="gap"><span class="ey">PRIMARY GAP</span><h2>${esc(rec.gap.toUpperCase())}</h2><p>${esc(rec.description)}</p></section><section class="recommend"><span class="ey">RECOMMENDED NEXT STEP</span><h2>${esc(rec.title)}</h2><p>${esc(rec.description)}</p><button class="primary" onclick="createWorkItem()">CREATE WORK ITEM →</button></section><div class="actions"><button onclick="editAssessment()">Edit Assessment</button><button onclick="closeAssessment()">Return to Portfolio</button></div></main>`}
function editAssessment(){state.section=0;renderAssessment()}
function createWorkItem(){const all=JSON.parse(localStorage.getItem(WORK)||'[]');const item={id:'work-'+Date.now(),title:state.results.title+' — '+state.agent.name,agentId:state.agent.id,type:'Optimization',priority:state.data.priority||'High',reason:state.results.description,createdAt:new Date().toISOString(),status:'open'};all.unshift(item);localStorage.setItem(WORK,JSON.stringify(all));alert('WORK ITEM CREATED\n\n'+item.title+'\n\nAdded to Portfolio.');closeAssessment();renderPortfolio()}
function renderPortfolio(){const list=document.getElementById('plist');if(!list)return;const all=allAssessments();list.innerHTML=products.map(p=>{const a=all[p.id];const status=a?.status==='completed'?'ASSESSED':a?.status==='in_progress'?'ASSESSING':'DISCOVERED';const readiness=a?.results?.overall??p.readinessPct;return `<article class="p" onclick="startAssessment('${p.id}')"><div class="row"><b>${esc(p.name)}</b><span>${readiness==null?'—':readiness+'/100'}</span></div><small>${esc(p.summary)}</small><div><span class="tag">${status}</span>${a?.status==='completed'?`<span class="tag">NEXT: ${esc(a.results.title)}</span>`:''}</div></article>`}).join('')}
function renderWork(){const el=document.getElementById('workList');if(!el)return;const all=JSON.parse(localStorage.getItem(WORK)||'[]');el.innerHTML=all.length?all.map(w=>`<div class="work"><b>${esc(w.title)}</b><span>${esc(w.priority)} · ${esc(w.status)}</span><small>${esc(w.reason)}</small></div>`).join(''):'<p class="muted">No work items created from assessments yet.</p>'}
window.startAssessment=startAssessment;window.closeAssessment=closeAssessment;window.nextSection=nextSection;window.prevSection=prevSection;window.jumpSection=jumpSection;window.setScale=setScale;window.toggleMulti=toggleMulti;window.completeAssessment=completeAssessment;window.createWorkItem=createWorkItem;window.editAssessment=editAssessment;
document.addEventListener('input',capture);document.addEventListener('change',capture);document.addEventListener('DOMContentLoaded',()=>{fetch('/product-readiness.json',{cache:'no-store'}).then(r=>r.json()).then(d=>{products=(d.products||FALLBACK).filter(p=>p.id!=='hoopdash');renderPortfolio()}).catch(renderPortfolio);renderPortfolio();renderWork();});
